---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  labels:
    app: fiufit
    tier: auth-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiufit
      tier: auth-microservice
  template:
    metadata:
      labels:
        app: fiufit
        tier: auth-microservice
    spec:
      containers:
      - name: auth
        image: marianocinalli/auth:v0.0.2
        imagePullPolicy: Always
        ports:
          - containerPort: 8002
            name: http-auth
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 128Mi
            cpu: "0.2"
