---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: fiufit
    tier: auth-service
spec:
  type: ClusterIP
  ports:
  - name: auth-svc
    protocol: TCP
    port: 8002
    targetPort: http-auth
  selector:
    app: fiufit
    tier: auth-microservice
